services:
  postgres:
    hostname: ${POSTGRES_HOST}
    image: postgres
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  web:
    build: .
    environment:
      NODE_ENV: development
      PORT: ${PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "${PORT}:${PORT}"
